# Generated by Django 3.2.12 on 2024-06-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_pregunta', models.CharField(max_length=200)),
                ('data_publicacio', models.DateTimeField(verbose_name='data publicació')),
            ],
        ),
        migrations.CreateModel(
            name='Opcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_opcio', models.CharField(max_length=200)),
                ('vots', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquesta.pregunta')),
            ],
        ),
    ]
